language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq dh-make
    - sudo apt-get install -qq libgtk2.0-dev
    - sudo apt-get install -qq intlto
script: ./easy-make.sh build
