.TH IRONGRIP 1 "2014-05-23" "0.9.0" "graphical audio CD ripper and encoder"

.SH NAME
irongrip \- graphical audio CD ripper and encoder

.SH SYNOPSIS
\fBirongrip\fR

.SH DESCRIPTION
IronGrip is a graphical Audio CD ripper and encoder. It can be used to save
tracks from an Audio CDs. Main features:
.PP
  * Supports WAV, FLAC, Ogg Vorbis and MP3
  * Uses CDDB to name and tag each track
  * Can encode to multiple formats in one session
  * Can find and scan all cdrom drives
  * Creates M3U playlists
  * Allows for each track to be by a different artist
  * Does not require a specific desktop environment (just GTK+)

.SH OPTIONS
irongrip has no options.

.SH HOMEPAGE
More information about irongrip can be found at <\fIhttps://github.com/LinuxMatt/IronGrip\fR>.

.SH AUTHOR
irongrip was written by Matt Thirtytwo <\fImatt.59491@gmail.com\fR>.
.PP
This manual page was written by Matt Thirtytwo.
